services:
  service-registry:
    image: service-registry
    container_name: service-registry-container
    ports:
      - "8761:8761"
    environment:
      - SERVICE_NAME=service-registry
      - EUREKA_CLIENT_SERVICEURL_DEFAULTZONE=http://service-registry:8761/eureka/
    networks:
      - microservices-net
    healthcheck:
      test: ["CMD-SHELL", "curl -f http://localhost:8761/actuator/health || exit 1"]
      interval: 10s
      timeout: 5s
      retries: 10
      start_period: 20s


  kafka:
    image: kafka
    container_name: kafka-container
    ports:
      - "8082:8082"
    environment:
      - SERVICE_NAME=kafka
      - EUREKA_CLIENT_SERVICEURL_DEFAULTZONE=http://service-registry:8761/eureka/
    depends_on:
      service-registry:
        condition: service_healthy
    networks:
      - microservices-net

  user-mgmt:
    image: user-mgmt
    container_name: user-mgmt-container
    ports:
      - "8081:8081"
    depends_on:
      service-registry:
        condition: service_healthy
    environment:
      - SERVICE_NAME=user-mgmt
      - EUREKA_CLIENT_SERVICEURL_DEFAULTZONE=http://service-registry:8761/eureka/
      - MYSQL_URL=jdbc:mysql://host.docker.internal:3307/microservice
      - MYSQL_USERNAME=root
      - MYSQL_PASSWORD=root
    networks:
      - microservices-net

  workflow:
    image: workflow
    container_name: workflow-container
    ports:
      - "8083:8083"
    depends_on:
      service-registry:
        condition: service_healthy
    environment:
      - SERVICE_NAME=workflow
      - EUREKA_CLIENT_SERVICEURL_DEFAULTZONE=http://service-registry:8761/eureka/      
      - MYSQL_URL=jdbc:mysql://host.docker.internal:3307/workflows
      - MYSQL_USERNAME=root
      - MYSQL_PASSWORD=root
    networks:
      - microservices-net

  api-gateway:
    image: api-gateway
    container_name: api-gateway-container
    depends_on:
      kafka:
        condition: service_started
      user-mgmt:
        condition: service_started
      workflow:
        condition: service_started
      service-registry:
        condition: service_healthy
    ports:
      - "8079:8079"
    environment:
      - SERVICE_NAME=api-gateway
      - EUREKA_CLIENT_SERVICEURL_DEFAULTZONE=http://service-registry:8761/eureka/
    networks:
      - microservices-net

networks:
  microservices-net:
    driver: bridge
